Quickbooks kick off
U-CRM/community pull request #7
Opened 2018-01-15 10:02 UTC by janprochazkacz

2018-01-16 12:31 UTC, UBNT-Petr commented
needs some Readme file to guide users:
This section is used to integrate UCRM with QuickBooks (oneway data migration from UCRM to QuickBooks)
1. First, configure your account settings in...
2. Use payments.php to import selected payments from UCRM to QB
3. Use ....

2018-01-17 09:39 UTC, keksa requested changes

2018-01-17 09:39 UTC, keksa commented on config.dist/quickbooks.php
> +const QUICKBOOKS_OAUTH_REDIRECT_URI = 'http://b3286fda.ngrok.io';
what should we put here?

2018-01-17 09:39 UTC, keksa commented on config.dist/quickbooks.php
> +const QUICKBOOKS_OAUTH_CODE = 'L011514360516YCAj1da2FEllWjYUBkVbnyH7ARuNWmJEp9eqN';
where do I get these values?

2018-01-17 09:39 UTC, keksa commented on scripts/quickbooksonline_import/invoices.php
> +        sprintf('SELECT * FROM Customer WHERE DisplayName LIKE \'%%UCRMID-%d%%\'', $ucrmClientId)
maybe limit 1?

2018-01-17 09:39 UTC, keksa commented on scripts/quickbooksonline_import/invoices.php
> +            'value' => 30
why 30?

2018-04-18 09:22 UTC, closed without merging